server:
  port: 8081
spring:
  application:
    name: spring-boot-example
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 60s
owl-job:
  config:
    namespace: ${spring.application.name}
    retry-attempts: 1
    
