/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderTools: typeof import('./src/components/container/tools/HeaderTools.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    HomeMenu: typeof import('./src/components/HomeMenu.vue')['default']
    I18nTool: typeof import('./src/components/container/tools/I18nTool.vue')['default']
    IconLocale: typeof import('./src/components/icon/IconLocale.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    Logo: typeof import('./src/components/icon/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/container/MenuItem.vue')['default']
    OutsideLink: typeof import('./src/components/container/tools/OutsideLink.vue')['default']
    OwlHeader: typeof import('./src/components/container/OwlHeader.vue')['default']
    OwlIcon: typeof import('./src/components/OwlIcon.vue')['default']
    OwlMenu: typeof import('./src/components/container/OwlMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tools: typeof import('./src/components/container/tools/index.vue')['default']
  }
}
